# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  tacshilohdistrictsservices:
    image: tacshilohdistrictsservices
    build:
      context: .
      dockerfile: TACShilohDistricts.Services/Dockerfile
    ports:
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
